CREATE TABLE TELEGRAM_TB (
    ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TEMPERATURE FLOAT(7,2) NOT NULL,
    HUMAN       INT(10) NOT NULL	
);

CREATE TABLE TELEGRAM_TB(
    ID SERIAL PRIMARY KEY AUTO_INCREMENT,
    TIME 
    TEMPERATURE DECIMAL(3,2) NOT NULL,
    HUMAN   DECIMAL(3,2) NOT NULL
)



SELECT * FROM TELEGRAM_TB;
INSERT INTO TELEGRAM_TB (TEMPERATURE,HUMAN) VALUES (31.5,92); NHAP GIA TRI
ALTER TABLE TELEGRAM_TB MODIFY TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP; #CHỈNH SƯA THUOCJ TINH 
//doc gia trị hang cuoi cung trong bảng
SELECT * FROM TELEGRAM_TB WHERE ID = (SELECT MAX(ID) FROM TELEGRAM_TB);
// XÓA MỘT HÀNG
DELETE FROM TELEGRAM_TB WHERE ID=1;