CREATE TABLE CLIMATE (
    ID INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TEMPERATURE DECIMAL(10,2) NOT NULL,
    HUMIDITY DECIMAL(10,2) NOT NULL,
    TEMPERATURE_SET DECIMAL(10,2) NOT NULL,
    HUMIDITY_SET DECIMAL(10,2) NOT NULL	
);
// tao table trong postgreSQL
CREATE TABLE CLIMATE(           
    ID SERIAL PRIMARY KEY,
    TIME TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    TEMPERATURE DECIMAL(3,2) NOT NULL,
    HUMINITY   DECIMAL(3,2) NOT NULL
);
//THAY DOI DATA TYPE
ALTER TABLE CLIMATE ALTER COLUMN TEMPERATURE SET DATA TYPE NUMERIC(7,2);
// them gia tri vao 1 hang co san
update CLIMATE set time=current_timestamp(0) where id=2;


SELECT * FROM CLIMATE;
INSERT INTO CLIMATE (TEMPERATURE,HUMINITY) VALUES (31.5,92); NHAP GIA TRI
ALTER TABLE CLIMATE MODIFY TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP; #CHỈNH SƯA THUOCJ TINH 
//doc gia trị hang cuoi cung trong bảng
SELECT * FROM CLIMATE WHERE ID = (SELECT MAX(ID) FROM CLIMATE);
// XÓA MỘT HÀNG
DELETE FROM CLIMATE WHERE ID=1;